markdown: redcarpet
highlighter: pygments

permalink: /:year/:month/:day/:title

title: Engineering in Time
tagline: 'Snapshots of Technology'
description: 'Snapshots of Technology'
url: http://blog.nictrix.net

author:
  name: 'Nick Willever'
  url: http://twitter.com/mdo

paginate: 5
paginate_path: "page/:num"

github:
  repo: https://github.com/nictrix/blog.nictrix.github.com
